name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 19.x
              uses: actions/setup-node@v3
              with:
                  node-version: 19.x
            - run: npm install -g pnpm
            - run: pnpm i --frozen-lockfile
            - run: pnpm build
